### PR TITLE
webserver: Customize port

### PR DESCRIPTION
**Pull request by StefanScherer**

### CODE REVIEW

**Comment by pennywisdom** [comment]
Hi Stefan have you seen [caddy](https://caddyserver.com/)? Its a pretty nice standalone web server for these kings of things. Lightweight at around 8Mb. Save you having to manage your own. If you did try it out, beware that there is an issue with volume mapping where the application does not parse that symlinks that windows creates when mounting volumes. I have submitted a PR which should be going in to the next release.

**Comment by StefanScherer** [comment]
Thanks @pennywisdom! Yes, I know caddy. This is still a useful "hello world" web server if you want to show some source code and how to build an app + Docker image.
Of course not for production ;-)

**Comment by StefanScherer** [comment]
OK, there is a Windows 64bit binary of Caddy to download. Time for a Docker image. You wanna try?

**Comment by pennywisdom** [comment]
Sure. We want to build from master rather than download though as my PR was accepted fixing the issue with symlinks / volume mapping but its not been released yet.

I have a Dockerfile I can submit as a PR. Will create that when I have a moment.

**Pull request merged**
