### PR TITLE
Create Docker TLS certs in Docker

### PR DESCRIPTION
**Pull request by StefanScherer**
Just a small fun Dockerfile to run the https://github.com/Microsoft/Virtualization-Documentation/tree/master/windows-server-container-tools/DockerTLS script on a Win2016 machine, but without installing OpenSSL directly on that machine. 

```
PS C:\> mkdir certs
PS C:\> docker run -e SERVER_NAME=$(hostname) -e IP_ADDRESSES="192.168.254.135 127.0.0.1" -v "$(pwd)\certs:c:\certs" stefanscherer/dockertls-windows
Creating Certificate Authority Keys
-Creating CA private key
-Creating CA public key
-Certificate Authority Keys Generated
Creating Client Key and Certifcate
-Verifying CA Keys
-Creating client key
-Creating cient certificate request
-Creating extended key use extention file
-Signing client request and generating certificate
-Creating PFX file for Windows
-Clening up extention file and cerficate request file
-Done Creating Client Certifcates!
Creating Server Key and Certifcate
-Verifying CA Keys
-Creating Server key
-Creating Server certificate request
-Creating extended key use extention file
-Signing Server request and generating certificate
-Cleaning up extention file and cerficate request file
-Done Creating Server Certifcates!
PS C:\> dir certs

    Directory: C:\Users\demo\certs

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       10/19/2016   2:26 PM           3380 ca-key.pem
-a----       10/19/2016   2:26 PM           1976 ca.pem
-a----       10/19/2016   2:26 PM           1810 cert.pem
-a----       10/19/2016   2:26 PM           1822 server-cert.pem
-a----       10/19/2016   2:26 PM           3294 server-key.pem
```

### CODE REVIEW

**Comment by friism** [comment]
very nice

**Comment by friism** [comment]
@StefanScherer the openssl setup should be hoisted out into the Dockerfile though...

**Comment by StefanScherer** [comment]
Yes. That would be cleaner. 

I think how the TLS setup could be simplified, eg. adding the config into a daemon.json on the Win2016 host. Like this omgwtfssl for Linux http://tech.paulcz.net/2016/01/secure-docker-with-tls/

Another thought is using the openssl commands directly without the Powershell script as it contains a fixed passphrase.

**Comment by StefanScherer** [comment]
Yes. That would be cleaner. 

I think how the TLS setup could be simplified, eg. adding the config into a daemon.json on the Win2016 host. Like this omgwtfssl for Linux http://tech.paulcz.net/2016/01/secure-docker-with-tls/

Another thought is using the openssl commands directly without the Powershell script as it contains a fixed passphrase.

**Pull request merged**
