### PR TITLE
Update caddy 0.10.7

### PR DESCRIPTION
**Pull request by StefanScherer**
Update Caddy 0.10.1, check if it still works.

### CODE REVIEW

**Comment by StefanScherer** [comment]
@pennywisdom Any ideas why Caddy 0.10.1 and 0.10.2 now responds with 301 Moved Permanently instead of 200 OK? I also tried it without the volumes, but it's the same.

**Comment by pennywisdom** [comment]
@StefanScherer i suspect it might be something to do with the Caddyfile. I will take a look also.

**Comment by pennywisdom** [comment]
Hmmm cant seem to work around it, likely a windows bug has been introduced. I will take a look in more detail when I can and submit a PR if needed. For now looks like 0.10.0 is what we need to keep here :(

**Comment by pennywisdom** [comment]
wonder if https://github.com/golang/go/commit/53003621720ff39c4745a76f76847123c27b01ea is affecting this also.

**Comment by StefanScherer** [comment]
I tried that and compiled caddy with that go version, but still "moved permanently"

**Comment by rismoney** [comment]
doesn't the caddy file now need to have a site address on the first line?

**Comment by StefanScherer** [comment]
OK, removed the redirect statement and updated Caddy to 0.10.7. Somewhere between 0.10.3 and now they may have changed to newer Golang version with the fix for mounted volumes.

**Pull request merged**
